/** 
 * https://github.com/atmulyana/nextCart
 **/
/*
This module is to genarate ID which is more random than mongo `ObjectId` but unique for a long-long time.
There are two functions for two collections: 'sesions' and 'customers'. The IDs from both collections will
be used by 'cart' collection. It's impossible that the ID generated by `createSessionId` will be the same
as that is generated by `createCustomerId` (will no collision all the time).
*/
import {customAlphabet} from 'nanoid';

const BASE64_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const nanoid = customAlphabet(BASE64_CHARS, 16);
export const createSessionId = () => {
    const id = nanoid(15);
    return id.substring(0, 7) + 'S' + id.substring(7);
};
export const createCustomerId = () => {
    const id = nanoid(15);
    return id.substring(0, 7) + 'C' + id.substring(7);
};
export default () => nanoid();